#!/bin/bash

#echo "Reading the binder..."
#python3 ./scripts/compileCollection.py

# Ititialization

mainmenu () {
	clear
	echo "Welcome to the menu."
	echo "Press 1 to check your collection."
	echo "Press 2 to check your binder."
	echo "Press 3 to check cards you have in your binder."
	echo "Press 4 to check cards you miss in your binder."
	echo "Press 5 to check a decklist."
	echo "Press 6 to check positions from a decklist in the binder."
	echo "Press 7 to check single cards from a decklist."
	echo "Press 8 to check cards missing from a decklist."
	echo "Press 9 to produce want list from all decklists."
	echo "Press 0 to check cards that should be added to the binder."
	echo "Press q to check cards that should be removed to the binder."
	echo "Press w to check common cards between any decks."
	echo "Press x to exit the script."
	read  -n 1 -p "Input Selection: " "mainmenuinput"
	echo ""

	if [ "$mainmenuinput" = "1" ]; then # Press 1 to check your collection.
		echo "Reading the collection..." 
		python3 ./scripts/printer.py collection
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "2" ]; then # Press 2 to check your binder.
		echo "Reading the binder..."
		python3 ./scripts/printer.py binder
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "3" ]; then # Press 3 to check cards you have in your binder.
		echo "Reading the binder..."
		python3 ./scripts/printer.py have
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "4" ]; then # Press 4 to check cards you miss in your binder.
		echo "Reading the binder..."
		python3 ./scripts/printer.py miss
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "5" ]; then # Press 5 to check a decklist.
		echo "Reading decks..."
		python3 ./scripts/printer.py decks
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "6" ]; then # Press 6 to check positions from a decklist in the binder.
		echo "Reading decks..."
		python3 ./scripts/deckChecker.py decks
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "7" ]; then # Press 7 to check single cards from a decklist.
		echo "Reading decks..."
		python3 ./scripts/deckChecker.py single
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "8" ]; then # Press 8 to check cards missing from a decklist.
		echo "Reading decks..."
		python3 ./scripts/deckChecker.py missing
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "9" ]; then # Press 9 to produce want list from all decklists.
		echo "Reading decks..."
		python3 ./scripts/deckChecker.py all
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "0" ]; then # Press 0 to check cards that should be added to the binder.
		echo "Compiling all decks..."
		python3 ./scripts/binderChecker.py
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "q" ]; then # Press q to check cards that should be removed to the binder.
		echo "Compiling all decks..."
		python3 ./scripts/coreChecker.py
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "w" ]; then # Press w to check common cards in two decks.
		echo "Reading lists..."
		python3 ./scripts/checkCommonCards.py
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	elif [ "$mainmenuinput" = "x" ]; then # Press x to exit the script.
		exit
	elif [ "$mainmenuinput" = "X" ]; then # Press x to exit the script.
		exit
	else
		echo "You have entered an invallid selection!"
		echo "Please try again!"
		echo ""
		echo "Press any key to continue..."
		read -n 1
		clear
		mainmenu
	fi
}

mainmenu